export const USER_SIGNUP_REQUEST ='USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS ='USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAIL ='USER_SIGNUP_FAIL'

export const USER_LOGIN_REQUEST ='USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS ='USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL ='USER_LOGIN_FAIL'

export const CREATE_CADIDATE_REQUEST ='CREATE_CADIDATE_REQUEST'
export const CREATE_CADIDATE_SUCCESS ='CREATE_CADIDATE_SUCCESS'
export const CREATE_CADIDATE_FAIL ='CREATE_CADIDATE_FAIL'

export const GET_EVENT_REQUEST ='GET_EVENT_REQUEST'
export const GET_EVENT_SUCCESS ='GET_EVENT_SUCCESS'
export const GET_EVENT_FAIL ='GET_EVENT_FAIL'

export const GET_EVENTBYID_REQUEST ='GET_EVENTBYID_REQUEST'
export const GET_EVENTBYID_SUCCESS ='GET_EVENTBYID_SUCCESS'
export const GET_EVENTBYID_FAIL ='GET_EVENTBYID_FAIL'

export const VOTING_REQUEST ='VOTING_REQUEST'
export const VOTING_SUCCESS ='VOTING_SUCCESS'
export const VOTING_FAIL ='VOTING_FAIL'


export const CONNECTION_REQUEST ='CONNECTION_REQUEST'
export const CONNECTION_SUCCESS ='CONNECTION_SUCCESS'
export const CONNECTION_FAILED ='CONNECTION_FAILED'
export const UPDATE_ACCOUNT ='UPDATE_ACCOUNT'

export const GET_SOCKET ='GET_SOCKET'



export const USER_LOGOUT ='USER_LOGOUT'